language: android
jdk: oraclejdk8
sudo: false
script: ./gradlew build
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'

before_install:
  - chmod +x gradlew
