language: android
jdk: oraclejdk8
sudo: false
script: ./gradlew build
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support



before_install:
  - chmod +x gradlew
