language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    = platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository

script: ./gradlew build
