language: android
jdk: oraclejdk8
sudo: false
script: "./gradlew build"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17

    deploy:
    provider: releases
    api_key:
    secure: dfd22c999916347884be11d8e0ce370a7a3a4a69
    file: app/build/outputs/apk/app-debug.apk
    skip_cleanup: true




   before_install:
    - chmod +x gradlew